### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by gladuo** [bradjasper/django-jsonfield#163] opened 2016-04-11 02:54 UTC
Due to Django 1.9.4:
`RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.`

Ah, I am not sure if you have plans to update the Jsonfield with Field.from_db_value, and if you do not have much time doing that, please tell us so we might could do something for it.

**Comment by frewsxcv** [comment] 2016-05-02 15:08
This is a duplicate of https://github.com/bradjasper/django-jsonfield/issues/153.

**Comment by dmkoch** [comment] 2017-03-02 05:03
Closing duplicate of #153

**Closed by dmkoch** 2017-03-02 05:03 UTC
